### PR TITLE
mau gabung ke master

### PR DESCRIPTION
**Pull request by Farino1702**
ngubah index.html dan readme.md

### CODE REVIEW

**Comment by hikimo** [comment]
Coba tambah 1 section lagi ya di index @Farino1702

**Comment by Farino1702** [comment]
@hikimo **sudah bos**

**Comment by hikimo** [comment]
lgtm!

**Review by hikimo — APPROVED** [review]
Cakep

**Comment by Farino1702** [comment]
thanks boss! can i have a raise?

**Pull request merged**
